spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mybatis-study?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 123321abc.
mybatis:
  mapper-locations: classpath:/mapper/*.xml