
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/springboot-cache?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 123321abc.
logging:
  level:
    anyu:
     springbootcache:
       mapper: debug
